#!/usr/bin/env Rscript   
# use chmod ug+x to make this file executable

suppressPackageStartupMessages(library(argparse))

parser = ArgumentParser()

parser$add_argument('-d', '--directory', type="character",
                    default="",
                    help="Directory where variables will be paste.")
parser$add_argument('-V', '--variables', nargs='+', type="character",
                    default="",
                    help="Name of the chose variables.")
parser$add_argument("-v", "--verbose", action="store_true", default=TRUE,
                    help="Print information")

args = parser$parse_args()

# Display the current parameters selected with argparse.
# parameters: 
#     args: argparse object
# Object generated by argparse with parser.parse_args() that
# contain all the selected parameters.
# returns: 
#     NULL
remind = function (args) {
    write("PARAMETERS:", stdout())
    n = length(args)
    args_name = names(args)
    for (i in 1:n) {
        write(paste0("    --", args_name[i], " ",
                     paste0(args[[i]], collapse=" ")), stdout())
    }
}

if (args$verbose) {
    remind(args)
}
if (args$directory == "") {
    write("Error : --directory is void\n", stderr())
    stop ()
}
if (all(args$variables == "")) {
    write("Error : --variables is void\n", stderr())
    stop ()
}

source_dir = "__all__"

if (!(file.exists(args$directory))) {
    dir.create(args$directory)
}
IN = args$variables
IN = paste0(unlist(IN), '.R')
n = length(IN)
OUT = paste0(1:n, '_', IN)
for (i in 1:n) {
    file.copy(file.path(source_dir, IN[i]),
              file.path(args$directory, OUT[i]))
}

if (args$verbose) {
    write("done", stdout())
}
